name: Build and Push Docker Image
on:
  pull_request: # trigger on all pull requests
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Variable
        id: set-variable
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            PR_BRANCH=${{ github.event.pull_request.head.ref }}
            echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
          else
            BRANCH=${{ github.ref }}
            echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # we need complete history for svu utility

      - name: Install svu
        run: |
          echo 'deb [trusted=yes] https://apt.fury.io/caarlos0/ /' | sudo tee /etc/apt/sources.list.d/caarlos0.list
          sudo apt update
          sudo apt install svu -yqq

      - name: Set Version with svu
        if: steps.check-branch.outputs.is_main_branch == 'true'
        run: |
          git tag $(svu next)
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # IMAGE_VERSION="$(svu next)"
      - name: Build Docker Image
        run: |
          DOCKER_IMAGE="myapp"
          DOCKER_IMAGE_TAG=""
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            DOCKER_IMAGE_TAG=$(echo ${{ github.sha }} | cut -c1-7)
          else
            DOCKER_IMAGE_TAG=$(svu next)
          fi
          docker build -t $IMAGE_TAG:$DOCKER_IMAGE_TAG .

      - name: Build Docker Image
        run: |
          IMAGE_TAG="myapp"
          IMAGE_VERSION="$(svu next)"
          docker build -t $IMAGE_TAG:$IMAGE_VERSION .
        working-directory: .
