name: Build and Push Docker Image
on:
  pull_request: # trigger on all pull requests
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG="myapp"
          IMAGE_VERSION=""
          docker build -t $IMAGE_TAG:$IMAGE_VERSION .
        working-directory: .
